"""Initial Migration

Revision ID: 38feba980319
Revises: b5e27a7897a5
Create Date: 2021-03-10 14:57:26.392021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38feba980319'
down_revision = 'b5e27a7897a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_hash', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_hash')
    # ### end Alembic commands ###
